# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.create(title: 'Jurassic Park' , description: "Director Steven Spielberg has been adapting beloved novels for the big screen since the early days of his career, beginning with Jaws. But it's his adaptation of 'Jurassic Park' in 1993 that makes the cut here. The film launched an entire franchise, consisting of two direct sequels and a rebooted Jurassic World trilogy. It turns out dinosaurs equal big box office numbers because the five Jurassic films have grossed a combined $4.8 billion. A third Jurassic World film is currently in production, and upon its release will surely push the cumulative box office past the $5 billion mark.", image:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/merlin-9962744-b0549fea-efaa-488b-8af6-3784b32be06e-mobilemasterat3x-1597517417.jpg?crop=1xw:1xh;center,top&resize=980:*")
Movie.create(title: 'The Hunger Games' , description: "The big-screen adaptation of the dystopian Hunger Games saga introduced the world to Jennifer Lawrence. Although it wasn't the star's first film role, it was, at the time, her largest. The big-screen series bowed in theaters in 2012. All three books were adapted—splitting the third book into two films. The Hunger Games saga grossed $2.9 billion across four films." , image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/hunger-games-1597957210.jpg?crop=1xw:1xh;center,top&resize=980:*")
Movie.create(title: 'Harry Potter' , description: "It should come as no surprise that the boy wizard conjures the top spot on this list. The eight films based on Rowling's seven fantasy novels have grossed a combined $7.7 billion at the global box office. That'll buy a lot of magic wands. The eighth film, Harry Potter and the Deathly Hallows: Part 2, which grossed $1.3 billion in 2011, is the highest-grossing book-to-movie adaptation in history. ", image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/hpss-1597956248.jpg?crop=1xw:1xh;center,top&resize=980:*")
Movie.create(title: 'The Lord of the Rings' , description: "Peter Jackson's entire trilogy of fantasy epics were filmed over the course of a single year, wrapping up production in December 2000. The first film was released in 2001 to a massive box office intake of $833 million. Combined, the trilogy grossed has over $2.9 billion at the global box office.", image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dominic-monaghan-merry-scene-elijah-wood-frodo-1597956337.jpg?crop=1xw:1xh;center,top&resize=980:*')